global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'domain']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'discord'

receivers:
  - name: 'discord'
    discord_configs:
      - webhook_url: 'http://example.com/placeholder-webhook'
        send_resolved: true
        title: '{{ if eq .Status "firing" }}🔴{{ else }}🟢{{ end }} {{ .CommonLabels.alertname }}'
        message: '{{ if eq .Status "firing" }}ALERT: {{ else }}RESOLVED: {{ end }}{{ .CommonLabels.domain }}'

inhibit_rules:
  # Inhibit API alerts if the website is down
  - source_match:
      alertname: 'WebsiteDown'
    target_match:
      alertname: 'APIDown'
    equal: ['domain']
    
  # Inhibit all alerts if Cloudflare DNS (1.1.1.1) is down
  # This indicates our internet connection is likely down
  - source_match_re:
      target: 'cloudflare-dns'
      status: 'down'
    target_match_re:
      alertname: '(WebsiteDown|APIDown)'
